#!/bin/bash

SUFIX_PATH="/home/kasparov/Documents/uni/third"
TEACHER=""
SUBJECT_NAME=""

# Reading the title of the document

TITLE=$(zenity --entry \
                --title="New latex document" \
                --width=300 \
                --text="Document title:")
ans=$?

if [ $ans -eq 0 ]; then
    if [ ${#TITLE} -eq 0 ]; then
        echo "Emty filename"
        exit 1
    fi
else
    echo "File creation has been canceled"
    exit 2
fi

# Reading the subject of the document

SUBJECT_SHORT=$(zenity --list \
                    --title="https://atareao.es" \
                    --height=350 \
                    --width=500 \
                    --text="Select a subject" \
                    --radiolist \
                    --column="" \
                    --column="Subject" \
                    1 "APWEORASE" \
                    2 "DIPAAP" \
                    3 "ESMEPAELDESO" \
                    4 "ESDAAP" \
                    5 "EVMEPAELDESO" \
                    6 "FOSO" \
                    7 "ING" \
                    8 "PRPAIT" \
                    9 "Tutoreo" )

ans=$?
if [ $ans -ne 0 ]; then
    echo "File creation has been canceled"
    exit 2
fi

case $SUBJECT_SHORT in
    APWEORASE)
        SUBJECT_NAME="Aplicaciones web orientadas a servicios"
        TEACHER="María Dolores Juarez Ramírez" ;;
    DIPAAP)
        SUBJECT_NAME="Diseño para apps"
        TEACHER="Cristian Estrada" ;;
    ESMEPAELDESO)
        SUBJECT_NAME="Estándares y métricas para el desarrollo de software"
        TEACHER="Myriam Soria García" ;;
    ESDAAP)
        SUBJECT_NAME="Estructuras de datos aplicadas"
        TEACHER="Ma Guadalupe Brizuela Gamiño" ;;
    EVMEPAELDESO)
        SUBJECT_NAME="Evaluación y mejora para el desarrollo de software"
        TEACHER="Cinthia Elizabeth Magallanes Donato" ;;
    FOSO)
        SUBJECT_NAME="Formación socio cultural"
        TEACHER="Luz Aurora Padilla Gutierrez" ;;
    ING)
        SUBJECT_NAME="Inglés"
        TEACHER="Luis Alejandro Gonzalez Zavala" ;;
    PRPAIT)
        SUBJECT_NAME="Principios para Iot"
        TEACHER="Ismael García Rangel" ;;
    Tutoreo)
        SUBJECT_NAME="Tutoreo"
        TEACHER="Ma Guadalupe Brizuela Gamiño" ;;
esac


# Reading the templeate

TEMPLEATE=$(<templeate.tex)

# Replacing the values of the templeate

TEMPLEATE=${TEMPLEATE//)TITLE/"$TITLE"}
TEMPLEATE=${TEMPLEATE//)SUBJECT/"$SUBJECT_NAME"}
TEMPLEATE=${TEMPLEATE//)TEACHER/"$TEACHER"}

# Creating the necesary folders

FOLDER_PATH="$SUFIX_PATH/$SUBJECT_SHORT/$TITLE"

printf "$FOLDER_PATH\n"

$(mkdir -p "$FOLDER_PATH/img")

# Copying the macros

$(cp macros.tex "$FOLDER_PATH")

# Writing the templeate

echo "$TEMPLEATE" >> "$FOLDER_PATH/$TITLE.tex"

# Opening the project in vs code

$(code $FOLDER_PATH)
